export const INDUSTRY_OPTIONS: string[] = [
  "Agriculture & Farming",
  "Mining, Quarrying, & Oil & Gas",
  "Utilities",
  "Construction & Contracting",
  "Manufacturing",
  "Wholesale & Distribution",
  "Retail & Storefronts",
  "Transportation & Logistics",
  "Technology & Digital Services",
  "Media, Marketing & Publishing",
  "Finance & Insurance",
  "Real Estate & Property Rentals",
  "Professional Services",
  "Holding Companies & Management",
  "Business Support & Facility Services",
  "Education & Training",
  "Healthcare & Family Services",
  "Arts, Entertainment & Recreation",
  "Public Administration",

  "Home & Property Services",
  "Personal & Consumer Services",
  "Restaurants & Food Service",
  "Hospitality & Lodging",
  "Automotive Services",
  "E-Commerce & Online Businesses",
  "Fitness & Wellness",
  "Childcare & Family Services",
  "Laundromats & Laundry Services",
];

export const INDUSTRY_SLUGS: Record<string, string> = {
  // Renamed legacy categories that keep old slugs/folders
  "Agriculture & Farming": "agriculture",
  "Mining, Quarrying, & Oil & Gas": "mining",
  "Utilities": "utilities",
  "Construction & Contracting": "construction",
  "Manufacturing": "manufacturing",
  "Wholesale & Distribution": "wholesale-trade",
  "Retail & Storefronts": "retail-trade",
  "Transportation & Logistics": "transportation",
  "Technology & Digital Services": "information",
  "Media, Marketing & Publishing": "media",
  "Finance & Insurance": "finance-insurance",
  "Real Estate & Property Rentals": "real-estate",
  "Professional Services": "professional-services",
  "Holding Companies & Management": "management",
  "Business Support & Facility Services": "admin-support-waste",
  "Education & Training": "education",
  "Healthcare & Family Services": "healthcare",
  "Arts, Entertainment & Recreation": "arts-entertainment",
  "Public Administration": "public-admin",

  // New categories with new slugs/folders
  "Home & Property Services": "home-services",
  "Personal & Consumer Services": "personal-services",
  "Restaurants & Food Service": "food-service",
  "Hospitality & Lodging": "hospitality",
  "Automotive Services": "automotive",
  "E-Commerce & Online Businesses": "ecommerce",
  "Fitness & Wellness": "fitness-wellness",
  "Childcare & Family Services": "childcare",
  "Laundromats & Laundry Services": "laundry",
};

export const INDUSTRY_IMAGES: Record<string, string[]> = {
  agriculture: [
    "agriculture/1.svg",
    "agriculture/2.svg",
    "agriculture/3.svg",
    "agriculture/4.svg",
    "agriculture/5.svg",
    "agriculture/6.svg",
    "agriculture/7.svg",
  ],
  mining: [
    "mining/1.svg",
    "mining/2.svg",
    "mining/3.svg",
    "mining/4.svg",
    "mining/5.svg",
    "mining/6.svg",
  ],
  utilities: [
    "utilities/1.svg",
    "utilities/2.svg",
    "utilities/3.svg",
    "utilities/4.svg",
    "utilities/5.svg",
    "utilities/6.svg",
  ],
  construction: [
    "construction/1.svg",
    "construction/2.svg",
    "construction/3.svg",
    "construction/4.svg",
    "construction/5.svg",
    "construction/6.svg",
  ],
  manufacturing: [
    "manufacturing/1.svg",
    "manufacturing/2.svg",
    "manufacturing/3.svg",
    "manufacturing/4.svg",
    "manufacturing/5.svg",
    "manufacturing/6.svg",
  ],
  "wholesale-trade": [
    "wholesale-trade/1.svg",
    "wholesale-trade/2.svg",
    "wholesale-trade/3.svg",
    "wholesale-trade/4.svg",
  ],
  "retail-trade": [
    "retail-trade/1.svg",
    "retail-trade/2.svg",
    "retail-trade/3.svg",
    "retail-trade/4.svg",
    "retail-trade/5.svg",
    "retail-trade/6.svg",
  ],
  transportation: [
    "transportation/1.svg",
    "transportation/2.svg",
    "transportation/3.svg",
    "transportation/4.svg",
    "transportation/5.svg",
    "transportation/6.svg",
  ],
  information: [
    "information/1.svg",
    "information/2.svg",
    "information/3.svg",
    "information/4.svg",
    "information/5.svg",
    "information/6.svg",
  ],
  media: [
    "media/1.svg",
    "media/2.svg",
    "media/3.svg",
    "media/4.svg",
    "media/5.svg",
    "media/6.svg",
  ],
  "finance-insurance": [
    "finance-insurance/1.svg",
    "finance-insurance/2.svg",
    "finance-insurance/3.svg",
    "finance-insurance/4.svg",
    "finance-insurance/5.svg",
    "finance-insurance/6.svg",
  ],
  "real-estate": [
    "real-estate/1.svg",
    "real-estate/2.svg",
    "real-estate/3.svg",
    "real-estate/4.svg",
    "real-estate/5.svg",
    "real-estate/6.svg",
  ],
  "professional-services": [
    "professional-services/1.svg",
    "professional-services/2.svg",
    "professional-services/3.svg",
    "professional-services/4.svg",
    "professional-services/5.svg",
    "professional-services/6.svg",
  ],
  management: [
    "management/1.svg",
    "management/2.svg",
    "management/3.svg",
    "management/4.svg",
  ],
  "admin-support-waste": [
    "admin-support-waste/1.svg",
    "admin-support-waste/2.svg",
    "admin-support-waste/3.svg",
    "admin-support-waste/4.svg",
    "admin-support-waste/5.svg",
    "admin-support-waste/6.svg",
  ],
  education: [
    "education/1.svg",
    "education/2.svg",
    "education/3.svg",
    "education/4.svg",
    "education/5.svg",
    "education/6.svg",
  ],
  healthcare: [
    "healthcare/1.svg",
    "healthcare/2.svg",
    "healthcare/3.svg",
    "healthcare/4.svg",
    "healthcare/5.svg",
    "healthcare/6.svg",
  ],
  "arts-entertainment": [
    "arts-entertainment/1.svg",
    "arts-entertainment/2.svg",
    "arts-entertainment/3.svg",
    "arts-entertainment/4.svg",
    "arts-entertainment/5.svg",
    "arts-entertainment/6.svg",
  ],
  "public-admin": [
    "public-admin/1.svg",
    "public-admin/2.svg",
    "public-admin/3.svg",
    "public-admin/4.svg",
    "public-admin/5.svg",
    "public-admin/6.svg",
  ],

  // New categories
  "home-services": [
    "home-services/1.svg",
    "home-services/2.svg",
    "home-services/3.svg",
    "home-services/4.svg",
    "home-services/5.svg",
    "home-services/6.svg",
  ],
  "personal-services": [
    "personal-services/1.svg",
    "personal-services/2.svg",
    "personal-services/3.svg",
    "personal-services/4.svg",
    "personal-services/5.svg",
    "personal-services/6.svg",
    "personal-services/7.svg",
  ],
  "food-service": [
    "food-service/1.svg",
    "food-service/2.svg",
    "food-service/3.svg",
    "food-service/4.svg",
    "food-service/5.svg",
    "food-service/6.svg",
  ],
  hospitality: [
    "hospitality/1.svg",
    "hospitality/2.svg",
    "hospitality/3.svg",
    "hospitality/4.svg",
    "hospitality/5.svg",
    "hospitality/6.svg",
  ],
  automotive: [
    "automotive/1.svg",
    "automotive/2.svg",
    "automotive/3.svg",
    "automotive/4.svg",
    "automotive/5.svg",
    "automotive/6.svg",
  ],
  ecommerce: [
    "ecommerce/1.svg",
    "ecommerce/2.svg",
    "ecommerce/3.svg",
    "ecommerce/4.svg",
    "ecommerce/5.svg",
    "ecommerce/6.svg",
  ],
  "fitness-wellness": [
    "fitness-wellness/1.svg",
    "fitness-wellness/2.svg",
    "fitness-wellness/3.svg",
    "fitness-wellness/4.svg",
    "fitness-wellness/5.svg",
    "fitness-wellness/6.svg",
  ],
  childcare: [
    "childcare/1.svg",
    "childcare/2.svg",
    "childcare/3.svg",
    "childcare/4.svg",
    "childcare/5.svg",
    "childcare/6.svg",
  ],
  laundry: [
    "laundry/1.svg",
    "laundry/2.svg",
    "laundry/3.svg",
    "laundry/4.svg",
    "laundry/5.svg",
    "laundry/6.svg",
  ],
};

// Public URL builder for Supabase Storage (PUBLIC bucket 'catalog')
export const imageUrl = (key: string) =>
  `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/catalog/industries/${key}`;

// Map industry label -> slug
export const toSlug = (industryLabel: string | null | undefined) => {
  if (!industryLabel) return null;
  return INDUSTRY_SLUGS[industryLabel] ?? null;
};